language: "node_js"
sudo: required
node_js:
  - "0.10"
services:
  - "mongodb"
before_install:
  - "npm install -g velocity-cli"
  - "curl -L http://git.io/ejPSng | /bin/sh"
script:
  - "velocity test-package --ci"